apiVersion: v1
kind: Service
metadata:
    name: dodobe-svc
    namespace: dodo
spec:
  type: ClusterIP
  # Traefik Ingress will route api.dodoclub.in to this service
  selector:
    app: dodobe
  ports:
   - port: 3002
     targetPort: 3002
