apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
 namespace: dodo
spec:
 serviceName: mongo-db-svc
 replicas: 1
 selector:
   matchLabels:
     app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     containers:
      - name: mongo
        image: mongo:7
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "dodo"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "dodopassword"
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
 volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 0.5Gi
